USE catconnect;

-- Demo user (password: password123) - BCrypt hash generated by Spring on first run; seed uses pre-generated hash
INSERT INTO users (email, password_hash, display_name, city) VALUES
('demo@catconnect.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Demo User', 'Cairo');

INSERT INTO vets (name, address, phone, latitude, longitude, rating, is_emergency, open_hours, city) VALUES
('Paws & Claws Veterinary', '15 Nile St, Zamalek', '+20-2-1234-5678', 30.0626, 31.2197, 4.8, FALSE, '9AM-8PM Daily', 'Cairo'),
('Emergency Pet Hospital 24/7', '42 Ring Rd, Maadi', '+20-2-9876-5432', 29.9602, 31.2569, 4.9, TRUE, '24 Hours', 'Cairo'),
('Whiskers Vet Clinic', '8 Tahrir Sq', '+20-2-5555-1111', 30.0444, 31.2357, 4.5, FALSE, '10AM-6PM Sun-Thu', 'Cairo'),
('Night Owl Emergency Vet', '100 Autostrada', '+20-2-7777-9999', 30.0500, 31.4000, 4.7, TRUE, '24 Hours', 'Cairo');

INSERT INTO cat_shops (name, address, phone, latitude, longitude, rating, city) VALUES
('Meow Mart', '22 Abbas El Akkad St', '+20-2-1111-2222', 30.0620, 31.3200, 4.6, 'Cairo'),
('Kitty Kingdom Supplies', '5 Mall of Egypt', '+20-2-3333-4444', 29.9720, 30.9430, 4.4, 'Giza'),
('Purrfect Pet Store', '12 Heliopolis', '+20-2-5555-6666', 30.0870, 31.3200, 4.7, 'Cairo');

INSERT INTO shelters (name, address, phone, email, website, description, capacity, city) VALUES
('Cairo Cat Rescue', '30 Desert Rd', '+20-2-8888-0001', 'info@cairocats.org', 'https://cairocats.org', 'Non-profit rescue for stray and abandoned cats.', 120, 'Cairo'),
('Happy Tails Shelter', '7 New Cairo', '+20-2-8888-0002', 'contact@happytails.eg', NULL, 'Adoption-focused shelter with foster network.', 80, 'Cairo'),
('Second Chance Felines', '3 Alexandria Corniche', '+20-3-8888-0003', 'help@secondchance.eg', NULL, 'Rehabilitation and rehoming for injured cats.', 60, 'Alexandria');

INSERT INTO care_knowledge (title, category, content, author) VALUES
('Kitten First Week Checklist', 'Kittens', 'Schedule vet visit within 48 hours. Provide warm bedding, kitten formula if under 4 weeks, and litter box with low sides.', 'Dr. Amira Hassan'),
('Signs of Urinary Blockage', 'Health', 'Straining in litter box, crying, licking genitals, or blood in urine require emergency vet visit immediately.', 'CatConnect Team'),
('Introducing a New Cat', 'Behavior', 'Use separate room for 1-2 weeks. Swap scents via blankets. Supervised short meetings before full integration.', 'Dr. Amira Hassan'),
('Dental Care at Home', 'Grooming', 'Brush teeth 2-3 times weekly with cat toothpaste. Dental treats help but do not replace brushing.', 'CatConnect Team'),
('Senior Cat Nutrition', 'Nutrition', 'Cats 11+ need easily digestible protein, joint supplements, and more frequent vet checkups every 6 months.', 'Dr. Amira Hassan');

INSERT INTO cat_memes (title, image_url, likes) VALUES
('Monday Mood', 'https://placekitten.com/400/300', 1240),
('If I Fits I Sits', 'https://placekitten.com/401/301', 892),
('Zoomies at 3AM', 'https://placekitten.com/402/302', 2103),
('Judgey Cat', 'https://placekitten.com/403/303', 567),
('Box > $200 Bed', 'https://placekitten.com/404/304', 3401);

INSERT INTO adoption_listings (user_id, cat_name, breed, age_months, gender, description, image_url, shelter_id, status) VALUES
(NULL, 'Luna', 'Domestic Shorthair', 8, 'Female', 'Playful tabby, vaccinated, good with kids.', 'https://placekitten.com/200/200', 1, 'AVAILABLE'),
(NULL, 'Shadow', 'Black Domestic', 14, 'Male', 'Calm indoor cat, neutered, loves laps.', 'https://placekitten.com/201/201', 1, 'AVAILABLE'),
(NULL, 'Miso', 'Siamese Mix', 24, 'Female', 'Talkative and affectionate senior sweetheart.', 'https://placekitten.com/202/202', 2, 'AVAILABLE'),
(1, 'Whiskers Jr', 'Persian', 6, 'Male', 'Fluffy kitten from private home, litter trained.', 'https://placekitten.com/203/203', NULL, 'AVAILABLE');

INSERT INTO lost_found_posts (user_id, post_type, cat_description, last_seen_location, contact_phone, image_url, status) VALUES
(1, 'LOST', 'Orange tabby, white paws, green collar "Max"', 'Zamalek, 15th St near Nile', '+20-100-111-2222', 'https://placekitten.com/300/250', 'ACTIVE'),
(NULL, 'FOUND', 'Grey longhair, very friendly, no collar', 'Maadi, Road 9', '+20-100-333-4444', 'https://placekitten.com/301/251', 'ACTIVE');

INSERT INTO cat_moments (user_id, caption, image_url, media_type, likes) VALUES
(1, 'Sunbeam nap champion', 'https://placekitten.com/150/150', 'IMAGE', 24),
(1, 'First day in the new cat tree!', 'https://placekitten.com/151/151', 'IMAGE', 56);

INSERT INTO moment_comments (moment_id, user_id, content) VALUES
(1, 1, 'So cute!'),
(2, 1, 'Looks like fun!');

INSERT INTO donation_campaigns (title, description, shelter_id, goal_amount, raised_amount, image_url, status) VALUES
('Winter Shelter Blanket Drive', 'Help us buy 200 warm blankets for rescued cats.', 1, 15000.00, 8750.00, 'https://placekitten.com/350/200', 'ACTIVE'),
('Medical Fund for Injured Strays', 'Emergency surgeries and vaccinations.', 2, 25000.00, 12000.00, 'https://placekitten.com/351/201', 'ACTIVE'),
('Food for 50 Foster Cats', 'Monthly dry and wet food supply.', 3, 8000.00, 3200.00, 'https://placekitten.com/352/202', 'ACTIVE');

INSERT INTO donations (campaign_id, user_id, amount, message) VALUES
(1, 1, 250.00, 'For all the fur babies!');
